/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package azure;

import azure.scenehandler.SceneHandlerFramework;
import javafx.application.Application;

public class App {

    public static void main(String[] args) {
        Application.launch(SceneHandlerFramework.class, args);
    }
}
